verbose: 1
git:
  requireCleanWorkingDir: true
  tagName: v${version}
  requireBranch:
    - master
  requireCommits: true
  commitMessage: Updated version to v${version} via release-it.
github:
  release: true
hooks:
  'after:bump': 'yarn run build'
